---
argument_specs:
  main:
    short_description: Create and manages Activation Keys
    description:
      - This role creates and manages Activation Keys.
    options:
      foreman_server_url:
        type: "str"
        required: false
        description: URL of the Foreman server. If the variable is not specified, the value of environment variable C(FOREMAN_SERVER_URL) will be used instead.
      foreman_username:
        type: "str"
        required: false
        description: Username accessing the Foreman server. If the variable is not specified, the value of environment variable C(FOREMAN_USERNAME) will be used instead.
      foreman_password:
        type: "str"
        required: false
        description: Password of the user accessing the Foreman server. If the variable is not specified, the value of environment variable C(FOREMAN_PASSWORD) will be used instead.
      foreman_validate_certs:
        type: "bool"
        required: false
        description: Whether or not to verify the TLS certificates of the Foreman server. If the variable is not specified, the value of environment variable C(FOREMAN_VALIDATE_CERTS) will be used instead.
      foreman_organization:
        type: "str"
        required: false
        description: Organization where configuration will be applied.
      foreman_activation_keys:
        type: "list"
        elements: "dict"
        required: true
        description: List of Activation Keys to manage.
